### ISSUE TITLE
which version of Pytorch, why i take the project to run,there are many problem? such as this code"hidden = hidden[:,running_seqs]"    wish you can give me some advise, thanks

### ISSUE THREAD

**Issue by KJ-Lin** [timbmg/Sentence-VAE#1]

**Comment by timbmg** [comment]
The PyTorch version is `0.3.1`.

For you problem with `hidden = hidden[:,running_seqs]`, could you please provide the error message?

**Comment by KJ-Lin** [comment]
thanks, the error message:   TypeError: indexing a tensor with an object of type torch.LongTensor. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.

**Comment by timbmg** [comment]
Thank you. I just tried again and it is running on my system. 

Did you change anything in the code?
How did you train the model? 
Also, could you print `hidden` and `running_seqs` before the error happens?

**Comment by KJ-Lin** [comment]
Thanks very much. The problem, which is the wrong of the version, has been dealt.

**Comment by timbmg** [comment]
So the error with the hidden update was also resolved by this?
