### ISSUE TITLE
maybe a bug in the train.py

### ISSUE THREAD

**Issue by linzhk** [timbmg/Sentence-VAE#18]
I got a bug in the following code:
`target = target[:, :torch.max(length).data[0]].contiguous().view(-1)`
and it fixed when I change code into:
`target = target[:, :torch.max(length).data].contiguous().view(-1)`

**Comment by kevinling0218** [comment]
the original code is supported by pytorch 0.4.X, which data[0] can be used

**Comment by timbmg** [comment]
fixed by #21
