### ISSUE TITLE
Error due to invalid data types

### ISSUE THREAD

**Issue by Deepayan137** [timbmg/Sentence-VAE#2]
Hi Tim,
          I guess you forgot to add `.cuda` to model at line no. 40, This is causing TypeError while trying to execute the `inference.py` code.
```
use_gpu = torch.cuda.is_available()
    if use_gpu:
        model=model.cuda()
    model.eval()
```
I guess the above snippet will fix it. :)

**Comment by timbmg** [comment]
Great, thank you! I added it 👍
