### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by nanguoshun** [timbmg/Sentence-VAE#23]
hi @timbmg, I am unable to access the dataset with the given command: 

_wget http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz_

It seems that this file has been deleted. Would you please help to provide a valid link?

Thanks a lot!

**Comment by timbmg** [comment]
I just tried and it works for me.

**Comment by nanguoshun** [comment]
hi @timbmg. Thanks a lot! It becomes normal for me now. Probably a temporarily accessing problem.
